// BATCH 11: Additional ELITE and PREMIUM careers for top performers

const batchElitePremiumExtra = [
  {
    title: 'Neurosurgeon',
    category: 'Healthcare',
    tier: 'ELITE',
    performanceLevel: 'EXCELLENT',
    academicRequirementScore: 12,
    description:
      'Diagnose and surgically treat disorders of the nervous system including the brain and spine, requiring extensive training and precision.',
    keySubjects: ['Biology', 'Chemistry', 'Physics', 'Mathematics'],
    requiredGrades: {
      Biology: 'A',
      Chemistry: 'A-',
      Physics: 'A-',
    },
    minimumMeanGrade: 'A-',
    marketDemand: 'High',
    jobProspects: [
      'Referral Hospitals',
      'Specialist Clinics',
      'Research Institutions',
      'Teaching Hospitals',
    ],
    salary: { entry: '250000', mid: '600000', senior: '1200000' },
    institutions: [],
    programDuration: '7-12 years',
    skillsRequired: [
      'Microsurgery',
      'Decision Making',
      'Team Leadership',
      'Analytical Thinking',
    ],
    careerPath: {
      entryLevel: { roles: ['Intern Doctor', 'Medical Officer'], experience: '0-2 years', description: 'Foundation in clinical medicine and surgery.' },
      midLevel: { roles: ['Registrar', 'Resident Neurosurgeon'], experience: '3-6 years', description: 'Specialist training and supervised surgical work.' },
      seniorLevel: { roles: ['Consultant Neurosurgeon'], experience: '7-12 years', description: 'Independent practice and sub-specialization.' },
      executiveLevel: { roles: ['Head of Neurosurgery'], experience: '12+ years', description: 'Department leadership, research, and training oversight.' },
    },
    certifications: [
      { name: 'Board Certification in Neurosurgery', provider: 'Relevant Medical Board', description: 'Post-residency specialist certification.' },
    ],
    industryTrends: ['Minimally Invasive Surgery', 'Neuro-navigation', 'Robotic Surgery'],
    featured: true,
    views: 0,
    saves: 0,
  },
  {
    title: 'Quantitative Analyst',
    category: 'Finance',
    tier: 'ELITE',
    performanceLevel: 'EXCELLENT',
    academicRequirementScore: 11,
    description:
      'Develop mathematical models to price securities, manage risk, and optimize portfolios in financial institutions.',
    keySubjects: ['Mathematics', 'Physics', 'Computer Science'],
    requiredGrades: { Mathematics: 'A', Physics: 'A-', },
    minimumMeanGrade: 'A-',
    marketDemand: 'Very High',
    jobProspects: ['Investment Banks', 'Hedge Funds', 'Asset Managers', 'FinTech'],
    salary: { entry: '180000', mid: '350000', senior: '700000' },
    institutions: [],
    programDuration: '4-6 years',
    skillsRequired: ['Stochastic Calculus', 'Statistical Modeling', 'Python', 'C++'],
    careerPath: {
      entryLevel: { roles: ['Junior Quant', 'Risk Analyst'], experience: '0-2 years', description: 'Model implementation and data analysis.' },
      midLevel: { roles: ['Quantitative Researcher'], experience: '3-6 years', description: 'Model research, pricing, and strategy.' },
      seniorLevel: { roles: ['Senior Quant', 'Team Lead'], experience: '7-10 years', description: 'Model governance and leadership.' },
      executiveLevel: { roles: ['Head of Quant'], experience: '10+ years', description: 'Department strategy and oversight.' },
    },
    certifications: [
      { name: 'CFA', provider: 'CFA Institute', description: 'Chartered Financial Analyst credential.' },
      { name: 'FRM', provider: 'GARP', description: 'Financial Risk Manager credential.' },
    ],
    industryTrends: ['ML in Finance', 'Alternative Data', 'XVA Modeling'],
    featured: false,
    views: 0,
    saves: 0,
  },
  {
    title: 'Cloud Solutions Architect (Enterprise)',
    category: 'Technology',
    tier: 'PREMIUM',
    performanceLevel: 'EXCELLENT',
    academicRequirementScore: 10,
    description:
      'Design, implement, and govern scalable cloud architectures, ensuring security, cost efficiency, and reliability across distributed systems.',
    keySubjects: ['Computer Science', 'Mathematics', 'Physics'],
    requiredGrades: {},
    minimumMeanGrade: 'B+',
    marketDemand: 'Very High',
    jobProspects: ['Cloud Providers', 'Consultancies', 'Enterprises', 'Startups'],
    salary: { entry: '150000', mid: '300000', senior: '550000' },
    institutions: [],
    programDuration: '4-6 years',
    skillsRequired: ['AWS/Azure/GCP', 'Systems Design', 'Networking', 'Security'],
    careerPath: {
      entryLevel: { roles: ['Cloud Engineer'], experience: '0-2 years', description: 'Implement cloud services and automation.' },
      midLevel: { roles: ['Senior Cloud Engineer'], experience: '3-5 years', description: 'Own domains and drive best practices.' },
      seniorLevel: { roles: ['Cloud Architect'], experience: '5-8 years', description: 'Lead architectures and migrations.' },
      executiveLevel: { roles: ['Head of Cloud'], experience: '8+ years', description: 'Cloud strategy and governance.' },
    },
    certifications: [
      { name: 'AWS Solutions Architect Professional', provider: 'Amazon Web Services', description: 'Advanced architecture certification.' },
      { name: 'Azure Solutions Architect Expert', provider: 'Microsoft', description: 'Enterprise architecture certification.' },
    ],
    industryTrends: ['Serverless', 'Zero-Trust Security', 'FinOps'],
    featured: false,
    views: 0,
    saves: 0,
  },
  {
    title: 'AI Research Scientist',
    category: 'Technology',
    tier: 'ELITE',
    performanceLevel: 'EXCELLENT',
    academicRequirementScore: 11,
    description:
      'Conduct cutting-edge research in artificial intelligence, develop novel models, and publish findings to advance the state of the art.',
    keySubjects: ['Computer Science', 'Mathematics', 'Statistics'],
    requiredGrades: { Mathematics: 'A', },
    minimumMeanGrade: 'A-',
    marketDemand: 'High',
    jobProspects: ['Research Labs', 'Big Tech', 'Startups', 'Universities'],
    salary: { entry: '180000', mid: '350000', senior: '700000' },
    institutions: [],
    programDuration: '4-8 years',
    skillsRequired: ['Deep Learning', 'Research Methods', 'Python', 'Papers/Patents'],
    careerPath: {
      entryLevel: { roles: ['Research Assistant'], experience: '0-2 years', description: 'Support research and experiments.' },
      midLevel: { roles: ['Research Scientist'], experience: '3-6 years', description: 'Lead projects and publish.' },
      seniorLevel: { roles: ['Senior Research Scientist'], experience: '6-10 years', description: 'Define research agenda.' },
      executiveLevel: { roles: ['Director of AI Research'], experience: '10+ years', description: 'Set strategy and partnerships.' },
    },
    certifications: [],
    industryTrends: ['Foundational Models', 'AI Safety', 'Efficient Training'],
    featured: true,
    views: 0,
    saves: 0,
  },
  {
    title: 'Petroleum Engineer',
    category: 'Engineering',
    tier: 'PREMIUM',
    performanceLevel: 'GOOD',
    academicRequirementScore: 9,
    description:
      'Design and develop methods for extracting oil and gas from deposits below the earth’s surface, optimizing production and safety.',
    keySubjects: ['Mathematics', 'Physics', 'Chemistry'],
    requiredGrades: {},
    minimumMeanGrade: 'B+',
    marketDemand: 'Medium',
    jobProspects: ['Energy Companies', 'Service Firms', 'Regulators'],
    salary: { entry: '120000', mid: '220000', senior: '400000' },
    institutions: [],
    programDuration: '4-5 years',
    skillsRequired: ['Reservoir Engineering', 'Simulation', 'Project Management'],
    careerPath: {
      entryLevel: { roles: ['Field Engineer'], experience: '0-2 years', description: 'Operations and data collection.' },
      midLevel: { roles: ['Reservoir Engineer'], experience: '3-6 years', description: 'Modeling and optimization.' },
      seniorLevel: { roles: ['Lead Engineer'], experience: '7-10 years', description: 'Project leadership.' },
      executiveLevel: { roles: ['Engineering Manager'], experience: '10+ years', description: 'Strategy and oversight.' },
    },
    certifications: [ { name: 'SPE Membership', provider: 'Society of Petroleum Engineers', description: 'Professional affiliation.' } ],
    industryTrends: ['Digital Oilfield', 'Enhanced Recovery', 'Energy Transition'],
    featured: false,
    views: 0,
    saves: 0,
  },
];

export default batchElitePremiumExtra;
